In [14]:
import numpy as np
import time

size = 1_000_000
np_array = np.arange(size)
py_list = list(range(size))


In [15]:
start = time.time()
np_array_result = np_array + 5
end = time.time()
print("NumPy array time:", end - start)


NumPy array time: 0.011401891708374023


In [11]:
start = time.time()
py_list_result = [x + 5 for x in py_list]
end = time.time()
print("Python list time:", end - start)


Python list time: 0.05754399299621582


In [11]:
import numpy
numpy.__version__


'2.3.4'

In [3]:
import numpy as np

# Creating a 3D list  (2 blocks, 2 rows, 3 columns)
list_3d = [
    [ [1, 2, 3], [4, 5, 6] ],
    [ [7, 8, 9], [10, 11, 12] ]
]

# Convert list to NumPy 3D array
arr_3d = np.array(list_3d)

print(arr_3d)
print("Shape:", arr_3d.shape)
print("Shape:", arr_3d.dtype)


[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
Shape: (2, 2, 3)
Shape: int64


In [5]:
import numpy as np

arr_int8 = np.array([10, 20, 30], dtype=np.int8)

print(arr_int8)
print("dtype:", arr_int16.dtype)


[10 20 30]
dtype: int16


In [6]:
import numpy as np

arr1 = np.array([10, 20, 30, 40])


In [ ]:
print(arr1[0])   
print(arr1[1])   
print(arr1[-1])  
print(arr1[-2])  

10
20
40
30


In [13]:
import numpy as np

arr = np.array([10, 20, 30, 40])

# Addition
print(arr + 5)      # add 5 to every element

# Subtraction
print(arr - 5)      # subtract 5 from every element

# Multiplication
print(arr * 2)      # multiply every element by 2

# Division
print(arr / 10)     # divide every element by 10


[15 25 35 45]
[ 5 15 25 35]
[20 40 60 80]
[1. 2. 3. 4.]


In [14]:
a = np.array([1, 2, 3])
b = np.array([10, 20, 30])

print(a + b)     # array addition
print(a - b)     # array subtraction
print(a * b)     # element-wise multiplication
print(a / b)     # element-wise division


[11 22 33]
[ -9 -18 -27]
[10 40 90]
[0.1 0.1 0.1]


In [15]:
arr2 = np.array([
    [1, 2],
    [3, 4]
])

print(arr2 + 10)    # add to all elements
print(arr2 * 3)     # multiply all elements


[[11 12]
 [13 14]]
[[ 3  6]
 [ 9 12]]


In [19]:
import numpy as np

arr = np.array([1, 2, 3])
copy_arr = arr.copy()

copy_arr[0] = 100

print("Original:", arr)     # [1 2 3]
print("Copy:", copy_arr)    # [100 2 3]


Original: [1 2 3]
Copy: [100   2   3]


In [21]:
arr = np.array([1, 2, 3])
view_arr = arr.view()

view_arr[0] = 100

print("Original:", arr)     # [100 2 3]
print("View:", view_arr)    # [100 2 3]


Original: [100   2   3]
View: [100   2   3]


In [22]:
import numpy as np

arr = np.array([10, 20, 30, 40, 50, 60])

result = np.split(arr, 3)
print(result)


[array([10, 20]), array([30, 40]), array([50, 60])]
